In [1]:
import numpy as np

#ganjal = np.array([1, 3, 5, 7, 9, 11, 13, 15])
ganjal = np.arange(1, 16, 2)  # Generates an array of odd numbers from 1 to 15
print("Array:", ganjal)

Array: [ 1  3  5  7  9 11 13 15]


In [2]:
berlima = np.array([5, 10, 15, 20, 25])
print("Array Berlima:", berlima)
print("Rata-rata:", np.mean(berlima))

Array Berlima: [ 5 10 15 20 25]
Rata-rata: 15.0


In [3]:
atuampeempat = np.array([[1,2], [3,4]])
print("gepenk:", atuampeempat.flatten())

gepenk: [1 2 3 4]


In [4]:
#arraytiga = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arraytiga = np.arange(1, 10).reshape(3, 3)
print("matriks 3x3:\n", arraytiga)
print("transpose:\n", arraytiga.T)

matriks 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
genat = np.array([2, 4, 6, 8, 10])

print("Array Genap:", genat)
print("Varian:", np.var(genat))
print("Deviasi Standar:", np.std(genat))

Array Genap: [ 2  4  6  8 10]
Varian: 8.0
Deviasi Standar: 2.8284271247461903


In [6]:
aray1 = np.array([1, 2, 3])
aray2 = np.array([4, 5, 6])
duadimensi = np.stack((aray1, aray2,), axis=1) 
print("jadi dua dimensi:\n", duadimensi)

jadi dua dimensi:
 [[1 4]
 [2 5]
 [3 6]]
