In [1]:
import numpy as np

atuampepuluh = np.arange(1, 11)
print("Array 1 sampai 10:", atuampepuluh)
print("Elemen ke-5:", atuampepuluh[4])

Array 1 sampai 10: [ 1  2  3  4  5  6  7  8  9 10]
Elemen ke-5: 5


In [11]:
araypuluh = np.arange(1, 51, 10)
print("Array 1 sampai 50 dengan step 10:", araypuluh)
print("Rata-rata:", np.mean(araypuluh))

Array 1 sampai 50 dengan step 10: [ 1 11 21 31 41]
Rata-rata: 21.0


In [ ]:
raykosong = np.zeros((3, 3), type=int)

raykosong[1] = np.array([5, 5, 5])
print("Array 3x3 dengan baris kedua diisi 5:\n", raykosong)

Array 3x3 dengan baris kedua diisi 5:
 [[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [12]:
a = np.arange(0, 16).reshape(4, 4)

print("Array 4x4:\n", a)
adiambil3 = np.delete(a, 2, axis=1) 
print("Diambil kolom ketiga jadinya: ", a[:, 2])
print("Ditebalikin: ", a[::, -1])

Array 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diambil kolom ketiga jadinya:  [ 2  6 10 14]
Ditebalikin:  [ 3  7 11 15]


In [5]:
x = np.random.randint(0,10,5)
y = np.random.randint(0,10,5)

print("Dot product dari x dan y:", np.dot(x, y))
print("Jumlah dan rata-rata dari hasil perkalian x dan y:\n", "x: ", np.sum(np.multiply(x, y)), "\n y:", np.mean(np.multiply(x, y)))

Dot product dari x dan y: 96
Jumlah dan rata-rata dari hasil perkalian x dan y:
 x:  96 
 y: 19.2
