In [51]:
import numpy as np

In [52]:
# Array 1D
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

1D Array: [1 2 3]


In [53]:
# Array 2D
arr2 = np.array([[1,2], [3,4]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2]
 [3 4]]


In [54]:
# Array 3D
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
# Membuat array dengan fungsi built-in
zeros = np.zeros((2, 3))
print("Array of zeros:\n", zeros)

ones = np.ones((3, 2))
print("Array of ones:\n", ones)

range_array = np.arange(0, 10, 2)
print("Array with range:\n", range_array)

linspace_array = np.linspace(0, 1, 5)
print("Array with linspace:\n", linspace_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array with range:
 [0 2 4 6 8]
Array with linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [56]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print("Penjumlahan:", a + b)
print("Pengurangan:", a - b)

print("Perkalian:", a * b)
print("Pembagian:", a / b)

Penjumlahan: [11 22 33]
Pengurangan: [ 9 18 27]
Perkalian: [10 40 90]
Pembagian: [10. 10. 10.]


In [57]:
print("elemen pertama:", a[0])
print("irisan elemen ke-1 hingga ke-2:", a[1:3])

elemen pertama: 10
irisan elemen ke-1 hingga ke-2: [20 30]


In [58]:
# Reshape
c = np.array([1, 2, 3, 4, 5, 6])
print("Reshape ke (2,3):\n", c.reshape(2, 3))

Reshape ke (2,3):
 [[1 2 3]
 [4 5 6]]


In [59]:
# Broadcasting
d = np.array([[1], [2], [3]])
e = np.array([10, 20, 30])
print("Hasil Broadcasting:\n", d + e)

Hasil Broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [62]:
# Operasi matriks
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print("Hasil Perkalian Matriks:\n", np.dot(mat1, mat2))
print("Transpose Matriks:\n", mat1.T)
print("Determinan Matriks:\n", np.linalg.det(mat1))

Hasil Perkalian Matriks:
 [[19 22]
 [43 50]]
Transpose Matriks:
 [[1 3]
 [2 4]]
Determinan Matriks:
 -2.0000000000000004
